#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo '🏗️👷 Checking your project before committing 👷‍♂️🏗️'
echo 'please be patient, this may take a while...'

echo '🎉 No error found: committing this now.... ✨🚀🏄‍♂️🍻'
